INSERT INTO accounts (org_id, category_id, website_name, website_url, login, password)
VALUES(1, 1, 'Facebook', 'http://www.facebook.com', 'mimi.chan@email.com', 'password123'),
      (1, 2, 'LinkedIn', 'http://www.linkedin.com', 'sebatian.mcdonald@email.com', '6ApRkn>0LxaKuDDK'),
      (1, 3, 'Hulu', 'http://www.hulu.com', 'mimi.chan@email.com', 'JevHi:L6zAJn-J>w'),
      (1, 4, 'Headspace', 'http://www.headspace.com', 'sebatian.mcdonald@email.com', 'UmMw6jxp0_gj2Rip'),
      (2, 1, 'Twitter', 'http://www.twitter.com', 'lady.gaga@email.com', 'hR!Jx})Ki0z4BQUT'),
      (2, 2, 'Indeed', 'http://www.ca.indeed.com', 'clover.grey@email.com', 'hw6~@z?QYi*@LWCn'),
      (2, 3, 'Netflix', 'http://www.netflix.com', 'lady.gaga@email.com', '0DX8vFuTa#X4TrmG'),
      (2, 4, 'Hello Fresh', 'https://www.hellofresh.ca/', 'clover.grey@email.com', '_Wjs=4o)8}+?e1By'),
      (3, 1, 'Instagram', 'http://www.instagram.com', 'alice.smith@email.com', 'B#qU0inCpDYE%kvF'),
      (3, 2, 'GitHub', 'http://www.github.com', 'alex.karev@email.com', 'mCegrvBGcFW]?902'),
      (3, 3, 'YouTube', 'http://www.youtube.com', 'alice.smith@email.com', 'z=X.T1WC!Hu^T:xD'),
      (3, 4, 'MyYoga', 'http://www.yoga.com', 'alex.karev@email.com', 'Gy#}W4Y-}0Dx_W0k'),
      (2, 1, 'Reddit', 'http://www.reddit.com', 'izzie.stevens@email.com', 'a%@0wqti%5#4C3!Q'),
      (2, 2, 'BambooHR', 'http://www.bamboohr.com', 'cristina.yang@email.com', 'NCRw1@cswr}CZUFX'),
      (2, 3, 'Crave', 'http://www.crave.ca', 'izzie.stevens@email.com', '*x}zBgWLkX%dH%E7'),
      (2, 4, 'Calm', 'http://www.calm.com', 'cristina.yang@email.com', 'w2u%sDMdEpq6Hf!n');
